### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by 11DE784A** [NISER-Software-Development-Group/NISER-Software-Development-Group.github.io#3]
Add and style stuff inside `<footer>`
Some inspiration:
* [MDN's footer](https://developer.mozilla.org/en-US/#nav-footer)
* [Materialize CSS's footer](https://materializecss.com/) <-- minimalist
* [GIthub's footer](https://github.com)
* [Jekyll's footer](https://jekyllrb.com/)

**Comment by PeithonKing** [comment]
Closing this issue because we shifted to a new site and this issue is not relevant anymore.
