### ISSUE TITLE
Clicking on navbar links should make the page scroll smoothly to respective sections

### ISSUE THREAD

**Issue by 11DE784A** [NISER-Software-Development-Group/NISER-Software-Development-Group.github.io#4]
Expected behaviour: Clicking a link on the navbar should make the page scroll smoothly
Current behaviour: Clicking a link instantly brings up the respective section

**Comment by feynhat** [comment]
set scroll-behavior to smooth in html's style.

**Comment by feynhat** [comment]
What I mean is, in `main.css`, set:

```
html {
  scroll-behavior: smooth;
}
```

**Comment by 11DE784A** [comment]
fixed.
